### ISSUE TITLE
ERROR [tera patch 56]

### ISSUE THREAD

**Issue by Notmacro** [meishuu/tera-proxy#22] opened 2017-06-06 10:51 UTC
![4444444](https://cloud.githubusercontent.com/assets/29227580/26825853/47423ec2-4abf-11e7-9aa7-d9f831b99337.jpg)

**Comment by notaslayer** [comment] 2017-06-06 19:25
any fix on this probleM?

**Comment by NXLinny** [comment] 2017-06-06 20:41
Im having this error too, probably its because the dungeon update that they released today. Maybe someone will need to release a update for the proxy to work again. : (

**Comment by wuaw** [comment] 2017-06-06 22:24
Update has been available for this protocol version for 2 days now, please update [tera-data](https://github.com/meishuu/tera-data) located in `tera-proxy/node_modules/tera-data`

**Comment by erikbernardo** [comment] 2017-06-07 00:39
I'm getting an error after update as well, but slightly different:

ERROR tera-proxy-sls: xml parser error
[xmldom error]  entity not found:&copy;

clues?

**Comment by meishuu** [comment] 2017-06-07 02:56
Duplicate of #21. See my comment there for details.

@erikbernardo Please feel free to open an issue for that error if it is preventing the proxy from working.

**Closed by meishuu** 2017-06-07 02:56 UTC

**Comment by erikbernardo** [comment] 2017-06-07 03:12
great, many thanks @meishuu .
